name: starfield_dart
description: A rewrite of the starfield site in Dart.
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  web: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
